version: '3'
services:
  api:
    container_name: api
    build: .
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ".:/usr/src/app"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    # restart: always
    volumes:
      - "data:/data/db"
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  data:
